#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443


FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["src/NormaliseAudio.Api/NormaliseAudio.Api.csproj", "src/NormaliseAudio.Api/"]
RUN dotnet restore "src/NormaliseAudio.Api/NormaliseAudio.Api.csproj"
COPY . .
WORKDIR "/src/src/NormaliseAudio.Api"
RUN dotnet build "NormaliseAudio.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NormaliseAudio.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NormaliseAudio.Api.dll"]

RUN apt-get update && apt-get install -y ffmpeg